// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
)

type File struct {
	ID        string
	Name      string
	FilePath  string
	Type      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
